annotations:
  artifacthub.io/category: monitoring-logging
  artifacthub.io/license: Apache-2.0
  artifacthub.io/screenshots: |
    - title: Cluster Overview
      url: https://raw.githubusercontent.com/headlamp-k8s/headlamp/screenshots/screenshots/cluster_overview.png
    - title: Cluster Chooser
      url: https://raw.githubusercontent.com/headlamp-k8s/headlamp/screenshots/screenshots/cluster_chooser.png
    - title: Nodes
      url: https://raw.githubusercontent.com/headlamp-k8s/headlamp/screenshots/screenshots/nodes.png
    - title: Resource edition
      url: https://raw.githubusercontent.com/headlamp-k8s/headlamp/screenshots/screenshots/resource_edition.png
    - title: Editor Documentation
      url: https://raw.githubusercontent.com/headlamp-k8s/headlamp/screenshots/screenshots/editor_documentation.png
    - title: Terminal
      url: https://raw.githubusercontent.com/headlamp-k8s/headlamp/screenshots/screenshots/terminal.png
apiVersion: v2
appVersion: 0.19.0
description: Headlamp is an easy-to-use and extensible Kubernetes web UI.
home: https://headlamp.dev/
icon: https://raw.githubusercontent.com/headlamp-k8s/headlamp/main/docs/headlamp_light.svg
keywords:
- kubernetes
- plugins
- kinvolk
- headlamp
- dashboard
- ui
- web
- monitoring
- logging
maintainers:
- name: kinvolk
  url: https://kinvolk.io/
name: headlamp
sources:
- https://github.com/headlamp-k8s/headlamp/tree/main/charts/headlamp
- https://github.com/headlamp-k8s/headlamp
type: application
version: 0.14.0
