apiVersion: v1
kind: Secret
metadata:
  name: oidc
type: Opaque
data:
{{- with .Values.config.oidc.clientID }}
  clientID: {{ . | b64enc | quote }}
{{- end }}
{{- with .Values.config.oidc.clientSecret }}
  clientSecret: {{ . | b64enc | quote }}
{{- end }}
{{- with .Values.config.oidc.issuerURL }}
  issuerURL: {{ . | b64enc | quote }}
{{- end }}
{{- with .Values.config.oidc.scopes }}
  scopes: {{ . | b64enc | quote }}
{{- end }}
